# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
#      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence
# whose values do not exceed four million,
# find the sum of the even-valued terms.
# Solution by Sam Gerber

# This method returns the sum of all even-valued terms of
# Fibonacci that do not exceed max
def sum_even_fibonacci(max)
  term1 = 1
  term2 = sum = 2

  loop do
    next_term = term1 + term2
    break if next_term > max
    sum += next_term if next_term % 2 == 0
    term1 = term2
    term2 = next_term
  end
  sum
end

puts sum_even_fibonacci(4_000_000)
