# Pentagon numbers
# Problem 44
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
# The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
# However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
# difference are pentagonal and D = |Pk − Pj| is minimised; 
# what is the value of D?

# Solution by Sam Gerber

def solution
  pentagon_numbers = [1, 5]
  results = []
  
  loop do
    # Add next term to the list
    n = pentagon_numbers.count + 1
    c =  n * (3 * n - 1) / 2
    puts "#{n}: #{c}"
    pentagon_numbers.reverse_each do |b|
      break if b < c / 2
      a = c - b
      z = b - a
      if Math.sqrt(24 * a + 1) % 6 == 5 && pentagon_numbers.include?(z)
        return [z, a, b, c]
      end
    end
    pentagon_numbers << c
    #break if results.count > 10
  end
  results
end
    
puts "solutions"
print solution